language: node_js
node_js:
  - "node"

env:
  - NODE_ENV=production

script:
  - npm install
  - npm run build


deploy:
  local_dir: 'dist'
  provider: pages
  skip_cleanup: true
  target_branch: gh-pages
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
